#install.packages("knitr")
#install.packages("kableExtra")
#install.packages("webshot")
#install.packages("htmlwidgets")

library(knitr)
library(kableExtra)
library(webshot)
library(htmlwidgets)

report_card <- data.frame(
  Managers = c("Alex", "Nit(h)esh", "Ishaan", "Ben", "Keshav + Arvind", "Kevin + Michael",
               "Nathan + Pranav", "Vinny + Mehul", "Sashank + Vikram", "Abhinav + Gautham",
               "Shatayu + Anirudh", "Raj"),
  Grade = c("B-", "N/A", "A", "B+", "D+", "C+", "F", "N/A", "A", "C-", "A-", "C"),
  Description = c(
    "Was off to an “A” start getting <b>Bo Nix</b>, filling the biggest need at Superflex with a QB that will have the starting role for at least 2 years. Sean Payton loves him so sky’s the limit for him in this Denver offense.<br><br>Outside of Nix, Alex walked away with <b>2 TEs (Sinnott & Stover) and a RB (B. Allen) </b> who all have high draft capital, but are all in questionable situations and <b> were all AfDP reaches (avg: 4.72 (2nd), total: 18.86 (2nd)).</b> With all the high potential WRs on the board, the choices were a bit curious, but this is also the manager that drafted CMC in the 1st round of a superflex startup and won the league so who am I to say. He definitely still has the best win now roster in the league, and is primed for a top seed again this year.",
    "See you at the 2025 Draft (probably not).",
    "With no 1st round pick, coming off a 3rd place finish, Ishaan had some options on how to build out this team. But he came into this draft, stayed composed, and got 3 flex players that could all end up in his starting lineup, as soon as week 1, despite being <b>2nd highest in average AnDP</b>.<br><br> <b> RBs Blake Corum and Dylan Laube </b> both have had many circulating rumors around their backfields, and are primed to be the RB2s come training camp, or maybe better. <b>WR Luke McCaffrey</b> is a McCaffrey that just got the most dynamic QB in recent CFB history, with a mid-WR core. The upside is there, and was exactly what Ishaan needed going into this next season. Of the 8 teams with 2-6 picks, probably my favorite draft at value",
    "Tough to give up Jamaar Chase in any scenario, but if there was any, this would be the one. Getting <b> QB Drake Maye </b> along with <b> Stafford and Addison </b> makes Ben's starting lineup much better than before. Pair that along with <b> WR Xavier Worthy </b> who has his doubts but will undoubtedly have high upside in the KC offense, Ben has put himself in a position to compete for now and the future. <br><br>With the next picks being 2 3rds and 2 4ths, he got some great potential at RB and WR, especially with <b> RB MarShawn Lloyd, being the best pick in the draft via AfDP of -6 </b> (drafted 6 spots later than consensus). <b> RB Ray Davis, and WRs D. Walker, and M. Washington </b> are also all high potential players in the best offenses in the league",
    "Keshav and Arvind came in with a 'Best Player Available' approach, drafting their 3rd QB in <b> JJ McCarthy </b>, despite being solid at QB with Allen and Prescott, and a heavy need at WR/flex. Would have liked to see them trade up/down potentially to one of the WR tiers, but now they potentially enter the season with 2ndRP <b> WR AD Mitchell </b> and Mike Williams at their starting flex spots. <br><br> The plus comes with their RBs at the end with <b> K. Vidal and W. Shipley </b> being fan favorites of the dynasty community right now, especially with Shipley, who turned out to be the best AfDP pick of the last 16 picks in the draft (-5.71).",
    "Kevin and Michael draft surrounded their most notable move being a trade with Raj, giving up a 2025 2nd to tier the 2.07 to the 3.01 and 3.03. An even trade via a trade calculator, and gives them an outside shot to compete this year with more <b> depth at WR with Burton and McMillan </b>, who are stuck to be WR 3s at best to start for 2024 but could end up as WR 2s by the end of the season. Additionally, two more backups in <b> QB Jordan Travis and RB Tyrone Tracy </b>, two of the more popular draft+stash players in dynasty gives them some youth to a relatively old core. Overall, they did have the <b> highest AfDP </b> at an average of 6.57, indicating there was potential to trade down for value.",
    "With many needs coming into the draft at flex and question marks at QB2, with a win now type roster, drafting <b>TE Brock Bowers</b> as your only pick in the first two rounds gives Nathan and Pranav the worst draft grade of 2024. Leaving with two <b>high upside WRs in Roman Wilson and Brendan Rice</b> is great, and gave them <b>the best AnDP at 4.84</b>. We'll see if trusting NFL draft capital pans out.",
    "See you at the 2025 Draft (probably).",
    "A perfect draft for their team build in any way you put it, by consolidating some value to get the debatably Dynasty WR1 in <b> Ja'maar Chase </b>, while also getting two first round <b> WRs in Odunze and Ladd</b>, who both could end up as the Rookie WR1 at the end of this year. And while they traded away their QB3 in Stafford, they grabbed two great QB values in <b> Penix and Rattler </b>, who are bound to be starters sometime in the next 2-3 years. <br><br> The only gap between an A+ and A is addressing their biggest need at RB. While they got <b> RB1 Jonathon Brooks </b>, and picked up <b> Irving </b> later on, they walk into the season as debatably the best team in QB and WR, but last in RB. Their contending window is now, and they had the capital to pay for a RB or push back some of their capital to trade for a RB mid-season but chose not to, drafting <b> WRs Troy Franklin and Malachi Corley </b>, to replace their traded Addison. Otherwise, its hard not to say this is the best dynasty team in the league, by a stretch.",
    "With two 4ths, Abhinav and Gautham got their two picks at decent value. They did end with the <b> highest AnDP </b> as they drafted <b> RB Audric Estime </b> over the likes of Guerendo and Shipley who went earlier in the NFL draft, but are in more set backup roles. <b> TE Erick All </b> was a AnDP steal as a player the Bengals drafted in the 3rd, but was taken with the 2nd to last pick in our draft.",
    "Firework start of the draft at the top, as they were able to trade down and get the player they may have drafted at the 1.02 anyways with <b> QB Jayden Daniels </b>, giving this team arguably the most high powered fantasy upside team between Lamar, Bijan, Achane, Aiyuk, and Jayden. <br><br> Where this grade falls a little is the risky upside picks to go along with their already high 'range of outcome team' with <b> WRs Xavier Legette, Keon Coleman, and Javon Baker,</b> all with the opportunity to be the WR1s on their team come season end, or be busts due to playstyle or age. But ending the draft with another 2 super high upside handcuff RBs in incredible offenses in <b> Isaac Guerendo and Jaylen Wright </b> means that we could EASILY look back at their draft in a year and see them as the clear winners if the cards turn the right way.",
    "Hard to give a bad grade to the team that got <b>Caleb, MHJ, and Nabers</b>, but not walking out with a 2nd QB as a rebuilding team with one of the most QB stacked drafts in history dragged this grade down to average / below average. <br><br> Filling up the rest of the draft with <b> 3 more top 40 pick WRs in BTJ, Pearsall, and Polk </b> shows a trust in NFL draft capital <b>(0.93 Avg AnDP, 1st in the league),</b> but one he's been stung on already last year (QJ, Mingo, Burks). Additionally, drafting for need a bit with <b> RB Trey Benson and TE Ben Sinnott </b> were both <b> bad AdDP and AnDP values </b> at their respective pick, and may have been better to trade those out for 2025 or 2026 picks considering the team is probably still a year out of contending in any form."
  )
)

report_card %>%
  kbl(escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), 
                full_width = F) %>%
  column_spec(1, bold = T) %>%
  column_spec(3, width = "30em") %>%
  add_header_above(c(" " = 1, "2024 Rookie Draft Report Card" = 2)) %>%
  save_kable("reportcard.png")
